var log = {
  welcome: '§3欢迎使用XOR存档加解密工具v1.0.',
  exit: '\n§d正在关闭软件...',
  tip1: '§3请输入目标存档level.dat所在文件夹路径',
  targetPath: '§3目标目录: %0',
  notDir: '§4目标不是文件夹, 请重试.',
  test: '§2已确认目标, 正在检测完整性...',
  missing: '§4缺失: %0',
  testSucc: '§2目标文件夹完整.\n§3请选择操作类型: 0.被动解密, 1.被动加密, 2.主动解密, 3.主动加密',
  testFail: '§4完整性测试未通过, 请检查后再试.',
  targetNotExist: '§4目标不存在.',
  invalidOp: '§4无效的操作类型',
  tip2: '§3正在进行被动解密.\n扫描文件夹...',
  error: '§4出现错误: %0',
  noEncFile: '§4未找到加密的文件.',
  le3EncFile: '§2找到加密文件: §6%0',
  gt3EncFile: '§2找到 §6%0 §2等§6%1§2个加密文件',
  createFolder: '§2正在创建文件夹...',
  cpFile: '§2正在复制源文件...',
  cping: '§6%0',
  decrypting: '§2正在解密...§6',
  decSucc1: '§2解密成功, 解密后存档已保存至§6%0.\n§3本次执行结束.',
  tip3: '§3请输入十六进制密钥. 若大于64bit将截取前64bit作为密钥. 自适应请留空.',
  invalidKey: '§4无效密钥, 请重试',
  autoKey: '§3已选择自适应密钥.',
  tip4: '§3正在进行主动解密.\n扫描文件夹...',
  tryGetKey: '§2尝试获取密钥...',
  getKeyFail: '§4获取密钥失败.\n§3本次执行结束.',
  getKeySucc: '§2获取密钥成功: §3%0',
  delExistFolder: '§2正在删除已有文件夹...'
};

exports.log = log;
