var log = {
  autoKey: '§3已选择自适应密钥.',
  avalTest: '§2正在进行ldb合理性测试...',
  avalTestFail: '§4发现魔数不对应的ldb文件, 可能解密失败或存档损坏.',
  avalTestSucc: '§2ldb文件魔数均合理, 测试通过.',
  cpFile: '§2正在复制源文件...',
  cping: '§6%0',
  createFolder: '§2正在创建文件夹...',
  decrypting: '§2正在解密...',
  decSucc1: '§2解密完成, 解密后存档已保存至§6%0.\n§3本次执行结束.',
  delExistFolder: '§2正在删除已有文件夹...',
  encrypting: '§2正在加密...',
  encSucc1: '§2加密完成, 加密后存档已保存至§6%0.\n§5本次执行结束.',
  error: '§4出现错误: %0',
  exit: '\n§d正在关闭软件...\x1b[0m',
  foundEncFile: '§4找到已加密文件, 无法再次执行加密.\n§5本次执行结束',
  getKeyFail: '§4获取密钥失败.\n§3本次执行结束.',
  getKeySucc: '§2获取密钥成功: §3%0',
  gt3EncFile: '§2找到 §6%0 §2等§6%1§2个加密文件.',
  invalidKey: '§4无效密钥, 请重试.',
  invalidOp: '§4无效的操作类型.',
  le3EncFile: '§2找到加密文件: §6%0',
  missing: '§4缺失: %0',
  noEncFile: '§4未找到加密的文件, 存档文件夹可能已解密.\n§3本次执行结束',
  noToEncFile: '§4未找到准备加密的文件, 存档文件夹可能损坏.\n§5本次执行结束',
  readyToEnc: '§5准备加密.',
  targetInvalid: '§4目标不存在或不是文件夹.',
  targetPath: '§3目标目录: %0',
  test: '§2已确认目标, 正在检测完整性...',
  testFail: '§4完整性测试未通过, 请检查后再试.',
  testSucc: '§2目标文件夹完整.\n§3请选择操作类型: 0.被动解密, 1.被动加密, 2.主动解密, 3.主动加密',
  tip1: '§3请输入目标存档level.dat所在文件夹路径.',
  tip2: '§3正在进行被动解密.\n扫描文件夹...',
  tip3: '§3请输入十六进制密钥. 若大于64bit将截取前64bit作为密钥. 自适应请留空.',
  tip4: '§3正在进行主动解密.\n扫描文件夹...',
  tip5: '§5正在进行被动加密.\n扫描文件夹...',
  tryGetKey: '§2尝试获取密钥...',
  welcome: '§3欢迎使用XOR存档加解密工具v3.0.'
};

exports.log = log;
