var log = {
  autoKey: '§3已选择自适应密钥.§r',
  avalTest: '§2正在进行ldb合理性测试...§r',
  avalTestFail: '§4发现魔数不对应的ldb文件, 可能解密失败或存档损坏.§r',
  avalTestSucc: '§2ldb文件魔数均合理, 测试通过.§r',
  cpFile: '§2正在复制源文件...§r',
  cping: '§6%0§r',
  createFolder: '§2正在创建文件夹...§r',
  decrypting: '§2正在解密...§r',
  decSucc1: '§2解密完成, 解密后存档已保存至§6%0.§r',
  delExistFolder: '§2文件夹已存在, 是否删除并覆盖[y/N]§r',
  encrypting: '§2正在加密...§r',
  encSucc1: '§2加密完成, 加密后存档已保存至§6%0.§r',
  error: '§4出现错误: %0',
  exit: '\n§d正在关闭软件...§r',
  finish: '§l§3执行结束, 按Ctrl+C退出或按Enter继续.§r',
  foundEncFile: '§4找到已加密文件, 无法再次执行加密.§r',
  getKeyFail: '§4获取密钥失败.§r',
  getKeySucc: '§2获取密钥成功: §3%0§r',
  gt3EncFile: '§2找到 §6%0 §2等§6%1§2个加密文件.§r',
  invalidKey: '§4无效密钥, 请重试.§r',
  invalidOp: '§4无效的操作类型.§r',
  le3EncFile: '§2找到加密文件: §6%0§r',
  missing: '§4缺失: %0§r',
  noEncFile: '§4未找到加密的文件, 存档文件夹可能已解密.§r',
  noToEncFile: '§4未找到准备加密的文件, 存档文件夹可能损坏.§r',
  readyToEnc: '§5准备加密.§r',
  scanning: '§5扫描文件夹...§r',
  selectOperation: "§3请选择操作类型: 0.被动解密, 1.被动加密, 2.主动解密§r",
  targetInvalid: '§4目标不存在或不是文件夹.§r',
  targetPath: '§3目标目录: %0§r',
  test: '§2已确认目标, 正在检测完整性...§r',
  testFail: '§4完整性测试未通过, 请检查后再试.§r',
  testSucc: '§2目标文件夹完整.§r',
  tip1: '§3请输入目标存档level.dat所在文件夹路径.§r',
  tip2: '§3正在进行被动解密.§r',
  tip3: '§3请输入十六进制密钥. 若大于64bit将截取前64bit作为密钥. 自适应请留空.§r',
  tip4: '§3正在进行主动解密.§r',
  tip5: '§5正在进行被动加密.§r',
  tryGetKey: '§2尝试获取密钥...§r',
  welcome: '§3欢迎使用XOR存档加解密工具v3.2.3.§r'
};

exports.log = log;
